# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- prod
- test
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    echo "Pipeline Workspace structure:"
    echo "Workspace path: $(Pipeline.Workspace)"
    ls -R $(Pipeline.Workspace)
  displayName: 'Display Pipeline Workspace structure'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/build'
    artifact: 'react080825Dev'
    publishLocation: 'pipeline'
    